# Generated by Django 4.2.3 on 2023-10-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('SALES', 'sales'), ('SUPPORT', 'support'), ('MANAGEMENT', 'management')], default='SUPPORT', max_length=25),
        ),
    ]
